Global:
  device: gpu
  epoch_num: 50
  log_smooth_window: 20
  print_batch_step: 20
  output_dir: /home/data_home/wudayu/experiments/multilingual_meme_ocr/svtrv2_line_recognition/04_model_training/runs/svtrv2_s_s10_to_target
  save_epoch_step: [0, 1]
  eval_epoch_step: [0, 100000]
  eval_batch_step: [0, 100000000]
  cal_metric_during_train: True
  pretrained_model: /home/data_home/wudayu/experiments/multilingual_meme_ocr/svtrv2_line_recognition/04_model_training/runs/svtrv2_s_s10_synthetic_pretrain/best_clean_dev_macro_cer.pth
  checkpoints:
  use_tensorboard: false
  infer_img:
  character_dict_path: &character_dict_path /home/data_home/wudayu/experiments/multilingual_meme_ocr/svtrv2_line_recognition/04_model_training/character_dict_hz_ug_kk_v1/character_dict.txt
  max_text_length: &max_text_length 120
  use_space_char: &use_space_char True
  save_res_path: /home/data_home/wudayu/experiments/multilingual_meme_ocr/svtrv2_line_recognition/04_model_training/runs/svtrv2_s_s10_to_target/predicts.txt
  use_amp: False
  grad_clip_val: 5.0
  project_name: svtrv2_s_s10_to_target
  seed: 20260725
  preprocess_protocol: P1_MSR_V3
  sampler_protocol: RATIO_SAMPLER_DDP_BALANCED_V2

Optimizer:
  name: AdamW
  lr: 0.00005000
  weight_decay: 0.01
  filter_bias_and_bn: True

LRScheduler:
  name: OneCycleLR
  warmup_epoch: 2
  cycle_momentum: False

Architecture:
  model_type: rec
  algorithm: SVTRv2
  Transform:
  Encoder:
    name: SVTRv2LNConvTwo33
    use_pos_embed: False
    dims: [96, 192, 384]
    depths: [3, 6, 3]
    num_heads: [3, 6, 12]
    mixer: [['Conv','Conv','Conv'],['Conv','Conv','Conv','FGlobal','Global','Global'],['Global','Global','Global']]
    local_k: [[5, 5], [5, 5], [-1, -1]]
    sub_k: [[1, 1], [2, 1], [-1, -1]]
    last_stage: false
    feat2d: True
  Decoder:
    name: RCTCDecoder

Loss:
  name: CTCLoss
  zero_infinity: True

PostProcess:
  name: CTCLabelDecode
  character_dict_path: *character_dict_path
  use_space_char: *use_space_char

Metric:
  name: RecMetric
  main_indicator: acc
  ignore_space: False
  is_filter: False

Train:
  dataset:
    name: RatioDataSetTVResize
    ds_width: True
    padding: False
    base_shape: [[64,64],[96,48],[112,40],[128,32]]
    base_h: 32
    data_dir_list:
      - /home/data_home/wudayu/experiments/multilingual_meme_ocr/svtrv2_line_recognition/04_model_training/msr_lmdb/P1_MSR_V3/target_train_u2
    transforms:
      - DecodeImagePIL:
          img_mode: RGB
      - CTCLabelEncode:
          character_dict_path: *character_dict_path
          use_space_char: *use_space_char
          max_text_length: *max_text_length
      - KeepKeys:
          keep_keys: ['image', 'label', 'length']
  sampler:
    name: RatioSampler
    scales: [[128,32]]
    first_bs: 32
    fix_bs: False
    divided_factor: [4,16]
    is_training: True
    max_ratio: 40
  loader:
    shuffle: True
    batch_size_per_card: 32
    drop_last: True
    max_ratio: 40
    num_workers: 4

Eval:
  dataset:
    name: RatioDataSetTVResize
    ds_width: True
    padding: False
    base_shape: [[64,64],[96,48],[112,40],[128,32]]
    base_h: 32
    data_dir_list:
      - /home/data_home/wudayu/experiments/multilingual_meme_ocr/svtrv2_line_recognition/04_model_training/msr_lmdb/P1_MSR_V3/target_dev_u2
    transforms:
      - DecodeImagePIL:
          img_mode: RGB
      - CTCLabelEncode:
          character_dict_path: *character_dict_path
          use_space_char: *use_space_char
          max_text_length: *max_text_length
      - KeepKeys:
          keep_keys: ['image', 'label', 'length']
  sampler:
    name: RatioSampler
    scales: [[128,32]]
    first_bs: 32
    fix_bs: False
    divided_factor: [4,16]
    is_training: False
    max_ratio: 40
  loader:
    shuffle: False
    batch_size_per_card: 32
    drop_last: False
    max_ratio: 40
    num_workers: 4
